language: php

php:
    - 7.3

branches:
    only:
        - master
    except:
        - dev


jobs:
    include:
        - stage: Tests
          before_script:
            - phpenv config-rm xdebug.ini
            - composer self-update
            - composer install
          script: php artisan Test
        - stage: Deploy
          script: skip
          deploy:
              cleanup: false
              provider: heroku
              strategy: api
              app: fullstack-penzugy
              api_key:
                  secure: Yu/XMooOP4OYqKBuvrQpc5ojx+3Omm5wx2g23DeZTj5PXscwUQBZTDpiF/fEP48gWRqPjlSVcUF3014GCQ5lszG4x3KIhZGDEJRS1ptV71LOWJWk44Eb3AhdxmviIAtssIYL9wrMiSa3zUoUMjogpxeUhP9FBmpUJO5dKtIEVuhJx0LCTiHZZMkV559VgK/aeaeYQ3fihXFUg4WglsvuVZUlxdEXCxrG8pKxlKSkMyDr79I0OCu3EzTCkT8Yl8vi0sUb58yVYxzOkPk5xKobdDYnbmobAYJhcuUewvR+GtGSiU13SA7mQ+XCLET/wmUqFAG1O2+fze51QN953pGBdUAPKjCROygR7xZXfB79yYfwxBYwF+VvfBxoa+W7Mytu77afim7W90nnmvi9obTHom62GTVmGBvl/LvUSCNmtuHWD8Q8O9Gy46PiaIPZSu1CUeczRR8cCHpmSoFJ15WnJg6WRiS2uit6JGT6sEE1f2lgFYN+ysTyJzXBvF912+pu2mMS606adSCvarISUoykdA5O1m3kAl9seSMkgu/VGnXW/Rn3ceemq8WyC5qXW2qCf/2MW4oEzZpyiDHY+xan7qarWCuvl/euRjMEoWf2r1/yBQn9XHka1543Dsd+R/MisnBpdwOSB30VgEbC+eDNNN+XZe+bl1PEk70ov1e72dc=

