os: linux

dist: xenial

branches:
    only:
        - master
    except:
        - dev

jobs:
    include:
        - stage: Backend Tests
          language: php
          php: 7.3
          before_install: cd backend
          before_script:
            - phpenv config-rm xdebug.ini
            - composer self-update
            - composer install
            - touch database/database.sqlite
            - cp .env.travis .env
            - php artisan key:generate
            - php artisan migrate --force
            - php artisan passport:install
          script: php artisan Test
        - stage: Backend Deploy
          language: php
          php: 7.3
          before_install: cd backend
          script: skip
          deploy:
              cleanup: false
              provider: heroku
              strategy: api
              app: fullstack-penzugy
              api_key:
                  secure: CnsUX/ZCDc0fY/1ZHUBF28WWTLQGlz3sMlzI17JQBqkVIG8wnWgMcS86KyC6Ac5ekBrZSi/OMZfkNULnOD+YCL5pWhS/QGtYH1z5LLYT3DjnYtd2xhVrkQX2/kdXEecMkPrnbPeMzTC481PZ1M3X7LYev5xUB81t6iacy56UYMC0aPFTz3WX/gLA8zgw5yyL5nKtmMiVbgCZ47Q6H+67XlQ1bszhJfvQNiolNUMRHNUab+njqNIcXk18ohMhpRSS97f3LcSFtrB35mHH0fWOMEBUd3X8N+Z9w8d/GCIWV/9i/xRh9o1ehg0S8jEGxZN/tpe2V4yszEntKBIhA4Kq+GAM0y9TD5PpRUOtS/8L3HNWFS/Tiw3xAfjqd6sYcZuYstTTR4czjEixQYhSWaodTUzZZGcj+udbxpu9I0e11vmvaFevtnrWOIV9wcPFnk3TSlxBt1widOs9uTGXROT+WyiQG83rCx/mqUg9emfz0h8vcUBnU81+7+M6yF+gP0nkQEl0QexD4ov/n2tDMwQquDvKbpkIKOVettPS7/bi1m7bGkQFKKl9TJ73ReGLYR1/WjFSNjBGX91m0RwnYEZDovkfrzbXcpcQr0nm0KRu7g6yRH5hHbpam2QZsMnsjyAfrDVIUVGXSfnd/qdTZ/P0FDBCkQs7dCjxEwo0xmyuVx4=

