os: linux

dist: xenial

branches:
    only:
        - master
    except:
        - dev

jobs:
    include:
        - stage: Backend Tests
          language: php
          php: 7.3
          before_install: cd backend
          before_script:
            - phpenv config-rm xdebug.ini
            - composer self-update
            - composer install
            - touch database/database.sqlite
            - cp .env.travis .env
            - php artisan key:generate
            - php artisan migrate --force
            - php artisan passport:install
          script: php artisan Test
        - stage: Backend Deploy
          language: php
          php: 7.3
          before_install: cd backend
          script: skip
          deploy:
              provider: heroku
              cleanup: false
              strategy: api
              app: fullstack-penzugy
              api_key:
                  secure: "s3P9CFrZNUVeqCiBjvGyShWel42d+FjK3EXBfYVfv0Lm99VrWrWSpw9DvEJcHzu+qcYmcRj+EhHYWFhKZk7KBD00A/3IhqN26oUOp4jjNkIClJl8QIusGxlnv2cPC3pGZk5tklaFPUxdCh3IPIIGpRod5CdyDSR22v0w8nlwlR+hNJ2Bc3bowLIl9NtAg/nadcMoVuOeNiVTN0EbrxSo8ErD4Sinku6zQ3lwk43sVA/U4LV1IpKoK+X6I8hWmcq/Jn1GGJ+dfjkj6K2xCg+4vcG9kLKLsGuBut1u6xIQQXNUsU4Wp2KBDYvhW3qrjjoPlFEFmfjCu22HbwFq8aVfTGIGeNC3rXg1lLI2idLhSI7vZ2BFpcGP0XXfhAEYVHjkplwh7wiaBRF62dBQRSnNA+do3C0Hc159wQkWN7RTFPEV/DejCGkh+ZNUi5P/AGNWi8U430P7c6TlwtfvyY53GPxDM2+w25bX1ycXLZHs8mm5Lw0hGuzJgVRMbvFCeoHlUVO0oJOl7UdEaO1XtZfzHIGOlSWndCGP+7gZwbZ/mVXW33I0b49wY4wNzc7rj1fCvXuNDAHSam6qo9flOXRdHSc2pGf+uMzXlXncSSzW2DRLGz/6YTC/Y0mrBNd3+DLZ8QKL20ol0Rk1wVsiGgA+Uf0sWoRt7KJg6YSxN9+pYuQ="
        - stage: Frontend Deploy
          language: node_js
          node_js: node
          before_install: cd frontend
          script: ng build --prod
          deploy:
              provider: pages
              cleanup: false
              github_token: $GITHUB_TOKEN
              local_dir: dist
              target_branch: gh-pages
              on:
                branch: master
